title: Marcos Bacon - Sound Design
description: >
  **Eu sou o Marcos Bacon.**
copyright: 2019 â€¢ Marcos Bacon
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: marcosbacon
facebook_username: pianobacon
# twitter_username: "#"
#linkedin_username: "#"
instagram_username: marcos.bacon
# pinterest_username:
# flickr_username:
github_username:  "marcosbacon"
# feed_icon: rss
email: "kakobacon@gmail.com"
plugins: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
